version: '3'
services:
  alterhop-api:
    container_name: alterhop-rest-api
    labels:
      com.oojobapi.description: "alterhop web app API server"
    build: ./server
    expose:
      - ${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    networks:
      - oooonetwork
  mongo:
    container_name: altmongo
    image: mongo
    restart: always
    ports:
    - ${MONGO_SERVER_PORT}:${MONGO_SERVER_PORT}
    networks:
      - oooonetwork

networks:
  oooonetwork:
    driver: bridge
