version: '3'
services:
  alterhop-api:
    container_name: alterhop-rest-api
    labels:
      com.oojobapi.description: "alterhop web app API server"
    build: ./server
    expose:
      - ${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    networks:
      - oooonetwork
  mongo:
    container_name: altmongo
    image: mongo
    restart: always
    ports:
    - ${MONGO_SERVER_PORT}:${MONGO_SERVER_PORT}
    networks:
      - oooonetwork
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
    networks:
      - oooonetwork
  frontend:
    container_name: alterhop-frontend
    labels:
      com.oojobapi.description: "alterhop web app client"
    build: ./client
    expose:
      - ${UI_SERVER_PORT}
    ports:
      - ${UI_SERVER_PORT}:${UI_SERVER_PORT}

networks:
  oooonetwork:
    driver: bridge
