version: '3'
services:
  alterhop-api:
    container_name: alterhop-rest-api
    labels:
      com.oojobapi.description: "alterhop web app API server"
    build: ./server
    environment:
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
      MONGO_SERVER_PORT: ${MONGO_SERVER_PORT}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    expose:
      - ${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - redis
      - mongo
    volumes:
      - ./server:/usr/local/app/server
      - /usr/local/app/server/node_modules
    networks:
      - oooonetwork
  mongo:
    container_name: altmongo
    image: mongo
    restart: always
    environment:
      MONGO_SERVER_PORT: ${MONGO_SERVER_PORT}
    ports:
    - ${MONGO_SERVER_PORT}:${MONGO_SERVER_PORT}
    networks:
      - oooonetwork
  redis:
    container_name: altredis
    image: redis
    restart: always
    environment:
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
    ports:
    - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
    networks:
      - oooonetwork
  frontend:
    container_name: alterhop-frontend
    labels:
      com.oojobapi.description: "alterhop web app client"
    build: ./client
    expose:
      - ${UI_SERVER_PORT}
    ports:
      - ${UI_SERVER_PORT}:${UI_SERVER_PORT}
    volumes:
      - ./client:/usr/local/app/client
      - /usr/local/app/client/node_modules

networks:
  oooonetwork:
    driver: bridge
